# Generated by Django 6.0.3 on 2026-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='employee_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
