# Generated by Django 6.0.2 on 2026-03-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_slug'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='product',
    #         name='unit_of_measure',
    #     ),
    ]
