# Generated by Django 6.0.2 on 2026-03-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_unit_of_measure'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='unit_of_measure',
        # ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_of_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitsmeasurement'),
            preserve_default=False,
        ),
    ]
