# Generated by Django 6.0.2 on 2026-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_unit_of_measure_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='productvariant',
        #     name='unique_variant_per_product',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='unit_of_measure',
        # ),
        migrations.AddField(
            model_name='productvariant',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'unit_of_measure', 'color', 'size'), name='unique_variant_per_product'),
        ),
    ]
