# Generated by Django 6.0.3 on 2026-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_productvariant_unique_variant_per_product_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='productvariant',
        #     name='unique_variant_per_product',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='unit_of_measure',
        # ),
        migrations.AddField(
            model_name='product',
            name='canonical',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
