# Generated by Django 6.0.3 on 2026-05-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
    ]
