# Generated by Django 6.0.3 on 2026-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_remove_historicalpurchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
