# Generated by Django 6.0.3 on 2026-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_historicalpurchaseorderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
