# Generated by Django 6.0.5 on 2026-08-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('procurement', '0010_historicalrequisition_requisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequisition',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='organization.department'),
        ),
    ]
