# Generated by Django 6.0.5 on 2026-08-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_historicalrequisition_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalRequisitionItem',
        ),
    ]
