# Generated by Django 6.0.5 on 2026-09-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_remove_requisitionitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequisition',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalrequisition',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='approved_by',
        ),
    ]
