# Generated by Django 6.0.5 on 2026-08-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstage',
            name='approver_is_department_head',
            field=models.BooleanField(default=False, help_text='If checked, the approver for this stage is the head of the department attached to the object being approved (ignores Approver Group).'),
        ),
    ]
